{{- if .Values.runtimeSecurity.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "datavision.fullname" . }}-default-deny-ingress
  labels:
    {{- include "datavision.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector: {}
{{- end }}
